name: Deploy to VM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install OpenVPN and Set Up Configuration
      - name: Set up OpenVPN
        run: |
          echo "Installing OpenVPN..."
          sudo apt-get update
          sudo apt-get install -y openvpn

          echo "Creating OpenVPN configuration file..."
          echo "$OPENVPN_CONFIG" > ~/soselab.ovpn

          echo "Starting OpenVPN connection..."
          sudo openvpn --config ~/soselab.ovpn --daemon

          echo "Waiting for OpenVPN connection to establish..."
          sleep 15

          echo "Verifying VPN connection..."
          ip addr show tun0 || (echo "VPN not connected. Exiting." && exit 1)

      # Deploy the application via SSH
      - name: Deploy Application
        run: |
          echo "Connecting to VM and deploying..."
          ssh -o StrictHostKeyChecking=no poxagpt@192.168.100.241 << 'EOF'
          echo "soselab707" | sudo -S /home/poxagpt/deployBack.sh
          EOF

      # Disconnect OpenVPN
      - name: Disconnect OpenVPN
        run: |
          echo "Disconnecting OpenVPN..."
          sudo pkill openvpn
