name: Deploy to VM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      - name: Enable TUN Device
        run: |
          sudo mkdir -p /dev/net
          if [[ ! -c /dev/net/tun ]]; then
            sudo mknod /dev/net/tun c 10 200
          fi
          sudo chmod 600 /dev/net/tun

      # Install OpenVPN
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      # Create OpenVPN Configuration File
      - name: Configure OpenVPN
        run: |
          echo "$OPENVPN_CONFIG" > ~/soselab.ovpn

      # Start OpenVPN and Verify
      - name: Start OpenVPN
        run: |
          sudo openvpn --config ~/soselab.ovpn --log /tmp/openvpn.log --daemon --verb 4
          sleep 30  # Increase sleep time to ensure VPN has time to connect
          ip addr show tun0 || (echo "VPN not connected. Exiting." && cat /tmp/openvpn.log && exit 1)

      # Deploy Application
      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no poxagpt@192.168.100.241 << 'EOF'
          echo "soselab707" | sudo -S /home/poxagpt/deployBack.sh
          EOF

      # Stop OpenVPN
      - name: Stop OpenVPN
        run: |
          sudo killall openvpn || echo "No OpenVPN process found."
