# This is a basic workflow to help you get started with Actions

name: Deploy to VM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn
          echo "$OPENVPN_CONFIG" > ~/soselab.ovpn
      
          echo "Starting OpenVPN..."
          sudo openvpn --config ~/soselab.ovpn > vpn_log.txt 2>&1 &
          sleep 10
      
          echo "OpenVPN logs:"
          cat vpn_log.txt
      
          echo "Checking VPN connection..."
          ip addr show tun0 || (echo "VPN not connected" && exit 1)

      - name: Verify VPN connection
        run: |
          ip addr show tun0 || (echo "VPN not connected" && exit 1)

      - name: Debug SSH Connection
        run: |
          ssh -v poxagpt@192.168.100.241 exit

      # Runs a set of commands using the runners shell
      - name: Deploy Application
        run: |
          ssh poxagpt@192.168.100.241 << 'EOF'
          echo "soselab707" | sudo -S /home/poxagpt/deployBack.sh
          EOF

      - name: Disconnect OpenVPN
        run: |
          # Kill OpenVPN process to disconnect
          sudo pkill openvpn
