name: Deploy to VM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install OpenVPN
      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      # Create OpenVPN configuration file from GitHub Secrets
      - name: Create OpenVPN configuration file
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > ./soselab.ovpn
          chmod 600 ./soselab.ovpn

      # Start VPN connection
      - name: Set up VPN connection with logs
        run: |
          sudo openvpn --config ./soselab.ovpn --daemon
          sleep 10
          sudo cat /var/log/syslog | grep openvpn

      # Test VPN connectivity
      - name: Test VPN connectivity
        run: |
          ping -c 4 192.168.100.241

      # Install sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # SSH into the server and run the deployment script
      - name: SSH into the server with password
        run: |
          sshpass -p "soselab707" ssh -o StrictHostKeyChecking=no poxagpt@192.168.100.241 "bash /home/poxagpt/deployBack.sh"

      # Stop OpenVPN
      - name: Stop OpenVPN
        run: |
          sudo killall openvpn || echo "No OpenVPN process found."