name: Deploy to VM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn
  
      - name: Set up VPN connection
        run: |
          sudo openvpn --config ./vpn/soselab.ovpn --daemon

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into the server with password
        run: |
          sshpass -p "soselab707" ssh -o StrictHostKeyChecking=no poxagpt@192.168.100.241 "bash /home/poxagpt/deployBack.sh"
      

      # Deploy Application
      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no poxagpt@192.168.100.241 << 'EOF'
          echo "soselab707" | sudo -S /home/poxagpt/deployBack.sh
          EOF

      # Stop OpenVPN
      - name: Stop OpenVPN
        run: |
          sudo killall openvpn || echo "No OpenVPN process found."
